### ISSUE TITLE
Running "npm run setup" results in Server 504 error occurred

### ISSUE THREAD

**Issue by eriktoyra** [contentful/starter-gatsby-blog#34]
## How to reproduce

I was follwing the "Gatsby Starter for Contentful" getting started guide and when running the `npm run setup` the error below occured.

- Node v10.15.0
- npm 6.9.0
- Gatsby CLI version: 2.7.53
- Gatsby version: 1.9.277

## Consequences

The project does start when doing a `npm run dev`, but it shows some React error after loading up the browser at http://localhost:8000.

```JavaScript
TypeError: Cannot read property '0' of undefined
RootIndex.render
src/pages/index.js:8
   5 | import ArticlePreview from '../components/article-preview'
   6 | 
   7 | class RootIndex extends React.Component {
>  8 |   render() {
   9 |     const siteTitle = get(this, 'props.data.site.siteMetadata.title')
  10 |     const posts = get(this, 'props.data.allContentfulBlogPost.edges')
  11 |     const [author] = get(this, 'props.data.allContentfulPerson.edges')
```

## Log output

```shell
» npm run setup -- --spaceId [hidden] --deliveryToken [hidden] --managementToken [hidden]

> contentful-starter-gatsby-blog@0.0.1 setup /Users/[removed-for-privacy-reasons]/starter-gatsby-blog
> npm install --no-save contentful-import yargs-parser axios chalk && node ./setup.js "--spaceId" "[hidden]" "--deliveryToken" "[hidden]" "--managementToken" "[hidden]"

npm WARN deprecated joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN friendly-errors-webpack-plugin@1.7.0 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

+ yargs-parser@14.0.0
+ chalk@2.4.2
+ axios@0.19.0
+ contentful-import@7.6.0
added 151 packages from 37 contributors, updated 5 packages and audited 25571 packages in 12.259s
found 1088 vulnerabilities (30 low, 17 moderate, 1040 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

Writing config file...

Config file /Users/[removed-for-privacy-reasons]/starter-gatsby-blog/.contentful.json written

┌──────────────────────────────────────────────────┐
│ The following entities are going to be imported: │
├─────────────────────────────────┬────────────────┤
│ Content Types                   │ 2              │
├─────────────────────────────────┼────────────────┤
│ Editor Interfaces               │ 2              │
├─────────────────────────────────┼────────────────┤
│ Entries                         │ 4              │
├─────────────────────────────────┼────────────────┤
│ Assets                          │ 4              │
├─────────────────────────────────┼────────────────┤
│ Locales                         │ 1              │
├─────────────────────────────────┼────────────────┤
│ Webhooks                        │ 0              │
└─────────────────────────────────┴────────────────┘
 ✔ Validating content-file
 ✔ Initialize client (1s)
 ✔ Checking if destination space already has any content and retrieving it (1s)
 ✔ Apply transformations to source data (1s)
 ✔ Push content to destination space
   ✔ Connecting to space (1s)
   ✔ Importing Locales (1s)
   ✔ Importing Content Types (4s)
   ✔ Publishing Content Types (2s)
   ✔ Importing Editor Interfaces (1s)
   ✔ Importing Assets (9s)
   ✔ Publishing Assets (2s)
   ✔ Archiving Assets (0s)
   ✔ Importing Content Entries (4s)
   ✔ Publishing Content Entries (3s)
   ✔ Archiving Entries (0s)
   ✔ Creating Web Hooks (0s)
Finished importing all data
┌───────────────────────┐
│ Imported entities     │
├───────────────────┬───┤
│ Locales           │ 1 │
├───────────────────┼───┤
│ Content Types     │ 2 │
├───────────────────┼───┤
│ Editor Interfaces │ 2 │
├───────────────────┼───┤
│ Assets            │ 2 │
├───────────────────┼───┤
│ Published Assets  │ 2 │
├───────────────────┼───┤
│ Archived Assets   │ 0 │
├───────────────────┼───┤
│ Entries           │ 4 │
├───────────────────┼───┤
│ Published Entries │ 4 │
├───────────────────┼───┤
│ Archived Entries  │ 0 │
├───────────────────┼───┤
│ Webhooks          │ 0 │
└───────────────────┴───┘
The import took a few seconds (22s)


The following 2 errors and 2 warnings occurred:

11:26:49 - Server 504 error occurred. Waiting for 2110 ms before retrying...
11:26:51 - Server 504 error occurred. Waiting for 2014 ms before retrying...
11:26:73 - VersionMismatch: Status: 409 - Conflict - Message:  - Request ID: 3b7e2c49dcb03dfb45e2fab72df3047b
11:26:89 - VersionMismatch: Status: 409 - Conflict - Message:  - Request ID: 60ab426470fc0dcf7db21632a7997f10

Stored the detailed error log file at:
/Users/[removed-for-privacy-reasons]/starter-gatsby-blog/contentful-import-error-log-1oxbsko5fp7k-2019-10-02T11-26-06.json
{ ContentfulMultiError: Errors occured
    at then (/Users/[removed-for-privacy-reasons]/starter-gatsby-blog/node_modules/contentful-import/dist/index.js:202:28)
    at tryCatcher (/Users/[removed-for-privacy-reasons]/starter-gatsby-blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/[removed-for-privacy-reasons]/starter-gatsby-blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/[removed-for-privacy-reasons]/starter-gatsby-blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/[removed-for-privacy-reasons]/starter-gatsby-blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/[removed-for-privacy-reasons]/starter-gatsby-blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/[removed-for-privacy-reasons]/starter-gatsby-blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/[removed-for-privacy-reasons]/starter-gatsby-blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/[removed-for-privacy-reasons]/starter-gatsby-blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
  name: 'ContentfulMultiError',
  errors:
   [ { ts: '2019-10-02T09:26:09.732Z',
       level: 'error',
       error: [Object] },
     { ts: '2019-10-02T09:26:09.899Z',
       level: 'error',
       error: [Object] } ] }
```

**Comment by eriktoyra** [comment]
Closing as no further work needed.
